
version: 2

sources:
   - name: raw
     database: meta-aura-484810-e5
     schema: gz_raw_data
     loader: bigquery
     description: GreenWeez Data
     tables:
       - name: raw_gz_product
         identifier: product
       - name: raw_gz_sales
         identifier: sales
       - name: raw_gz_ship
         identifier: ship
