
version: 2

sources:
   - name: raw
     database: meta-aura-484810-e5
     schema: gz_raw_data
     loader: bigquery
     description: GreenWeez Data
     tables:
       - name: product
         identifier: raw_gz_product
         description: list of products
         columns:
          - name: products_id
            description: private key
            tests:
              - unique
              - not_null
          - name: purchase_cost
            description: cost to buy the product
       - name: sales
         identifier: raw_gz_sales
         description: list of orders
         columns:
         - name: orders_id
         - name: date_date
         - name: pdt_id
       - name: ship
         identifier: raw_gz_ship
         description: information on ship fees and cost (included logistic costs)
         columns:
         - name: orders_id
           tests:
             - unique
             - not_null
       - name: adwords
         identifier: raw_gz_adwords
         description: list of Ad by Adwords
       - name: bing
         identifier: raw_gz_bing
         description: list of Ad from Bing
       - name: criteo
         identifier: raw_gz_criteo
         description: list of Ad from Criteo
       - name: facebook
         identifier: raw_gz_facebook
         description: list of Ad from Facebook
             
models:
  # ----------------------------------------------------------------------------
  # A. Modèles de Staging (nettoyage & renommage)
  # ----------------------------------------------------------------------------
  
  - name: stg_raw__raw_gz_sales
    description: "Renommage de l'id des produits"

  - name: stg_raw__product
    description: "Cast et renommage du prix des produits"

  - name: stg_raw__ship
    description: "Renommage des colonnes de coûts"

  - name: stg_raw__adwords
    description: "Renommage de la colonna camPNG_name et conversion de la colonne ad_cost en FLOAT64"
  
  - name: stg_raw__bing
    description: "Renommage de la colonna camPNG_name et conversion de la colonne ad_cost en FLOAT64"

  - name: stg_raw__criteo
    description: "Renommage de la colonna camPNG_name et conversion de la colonne ad_cost en FLOAT64"

  - name: stg_raw__facebook
    description: "Renommage de la colonna camPNG_name et conversion de la colonne ad_cost en FLOAT64"
    
  # ----------------------------------------------------------------------------
  # B. Modèles Intermédiaires (calculs / aggrégations / jointures nécessaires)
  # ----------------------------------------------------------------------------
  
  - name: int_sales_margin
    description: "Calcul de la marge ligne à ligne (avec Sales et Product)."
    columns:
      - name: margin
        description: "Revenue - Purchase Cost"
      - name: purchase_cost
        description: "Coût d'achat (quantité * prix d'achat)"

  - name: int_orders_margin
    description: "Agrégation de la marge au niveau de la commande (orders_id)"
    columns:
      - name: orders_id
        tests:
          - unique
          - not_null
      - name: margin
        description: "Somme des marges de tous les produits de la commande"

  - name: int_orders_operational
    description: "Marge opérationnelle (marge - coûts logistiques)"
    columns:
      - name: orders_id
        tests:
          - unique
          - not_null              
      - name: operational_margin
        description: "Marge + shipping fee - (log cost + ship cost)"

  - name: int_campaign
    description: "Fusion des 4 tables campaigns (Adwords, Bing, Criteo et Facebook) en une seule"
    tests:
      - unique:
          column_name: "(date_date || '-' || campaign_key)"

  - name: int_campaigns_day
    description: "Agrégation des campagnes par date"
    columns:
      - name: date_date
        tests:
          - unique
          - not_null
      - name: ads_cost
        description: "Coût journalier toute campagne confondu"

  # ----------------------------------------------------------------------------
  # C. Modèles Marts (Finance ici)
  # ----------------------------------------------------------------------------

  - name: finance_days
    description: "KPIs financiers agrégés par jour, table principale pour le dashboard financier"
    columns:
      - name: date_date
  
  - name: finance_campaigns_day
    description: "KPIs financiers agrégés par jour, table principale pour le dashboard financier en rajoutant les éléments sur les frais de publicité"
    columns:
      - name: date_date